[project]
name = "data-dojo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7.9"
dependencies = [
    "graphviz>=0.20.1",
    "jupyter>=1.1.1",
    "pandas>=1.3.5",
    "plotly>=5.18.0",
    "scikit-learn>=1.0.2",
    "seaborn>=0.12.2",
]
